services:
  - type: web
    name: gym-app-backend
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npx turbo -F @gymApp/db db:generate && npx turbo build --filter=server...
    startCommand: npm run start --filter=server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gym-app-db
          property: connectionString
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: gym-app-db
    plan: free
